spring.application.name=serviceRegistry
server.port=8080
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Enable/disable restart
spring.devtools.restart.enabled=true

# Exclude resources from restart
spring.devtools.restart.exclude=static/**,public/**

# Enable/disable LiveReload
spring.devtools.livereload.enabled=true